# Generated by Django 5.2.17 on 2026-09-08 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('location_name', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='reconciliation.organization')),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='SystemBEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_ref', models.CharField(max_length=100)),
                ('normalized_record_ref', models.CharField(db_index=True, max_length=50)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_b_entries', to='reconciliation.location')),
            ],
        ),
        migrations.CreateModel(
            name='SystemARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=50)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_a_records', to='reconciliation.location')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('location', 'record_id'), name='unique_a_record_per_location')],
            },
        ),
    ]
