# Generated by Django 5.2.17 on 2026-09-08 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='systemarecord',
            name='unique_a_record_per_location',
        ),
        migrations.AddField(
            model_name='systemarecord',
            name='import_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='systemarecord',
            name='raw_location_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='systemarecord',
            name='source_row_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systembentry',
            name='entry_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='systembentry',
            name='import_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='systembentry',
            name='raw_location_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='systembentry',
            name='source_row_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='systemarecord',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_a_records', to='reconciliation.location'),
        ),
        migrations.AlterField(
            model_name='systemarecord',
            name='record_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='systembentry',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_b_entries', to='reconciliation.location'),
        ),
        migrations.AlterField(
            model_name='systembentry',
            name='normalized_record_ref',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='systembentry',
            name='record_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='systemarecord',
            constraint=models.UniqueConstraint(fields=('raw_location_id', 'record_id'), name='unique_a_record_per_raw_location'),
        ),
    ]
